SET FOREIGN_KEY_CHECKS=0;
USE `corejavasba`;

DROP TABLE IF EXISTS `event`;
CREATE TABLE `event`(
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(50) NOT NULL,
	`date` DATE NOT NULL
) DEFAULT CHARSET=UTF8;